name: a01_HdD

on:
  workflow_dispatch:

jobs:
  Mi_inicio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "varios"
        run: |
          git config user.name "Angel"
          git config user.email "U21232253@utp.edu.pe"
          
